### ISSUE TITLE
Are there any tutorial style examples?

### ISSUE THREAD

**Issue by Cortlandd** [LumiGuide/haskell-opencv#1]

**Comment by roelvandijk** [comment]
Most examples are in the documentation. Like [this one](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-Features2d.html#g:3) on descriptor matching. Note that all examples in the documentation are actually compiled as part of the test suite. The images in the documentation are generated by these examples.

In the future it would also be nice to have some complete example programs, tutorial style.

**Comment by Cortlandd** [comment]
Tutorial is what I was referring to. I'll likely just start hacking at it, and write a tutorial on my discoveries.

**Comment by basvandijk** [comment]
Let us know if you run into any kind of difficulties and when something is unclear. I'm looking forward to your tutorial!

**Comment by Cortlandd** [comment]
No problem. Fairly a beginner to Haskell. Looking to learn as much as I can. So far, I've figured out how to tell which functions are missing that are in C++CV(opencv 3.1), just have to figure out the logic. Right now, I'm trying to implement resizeWindow function.

**Comment by basvandijk** [comment]
`resizeWindow :: Window -> Int32 -> Int32 -> IO ()` seems like a good function to start contributing. I'm looking forward to your pull request! ;-)

**Comment by Cortlandd** [comment]
Oh I was gonna ask, because my C++ is **only** an introduction course from Microsoft on Edx,
What is this here (well, of course a function): 
https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window.cpp#L548

the parameters are about the same as here: 
https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window.cpp#L176

but I'm still confused? Not much actual logic. And what exactly is "CV_IMPL" ?

**Comment by roelvandijk** [comment]
There is a lot of [preprocessor](https://en.wikipedia.org/wiki/C_preprocessor) stuff going on. 

`CV_IMPL` is a OpenCV specific CPP macro that probably expands to some export definition (like __declspec in windows).

The first link you provided (line 548) is entirely contained in the [`#else` branch](https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window.cpp#L501) of an [`#if` statement](https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window.cpp#L494).

It is the code block for when you have no GUI libraries installed. That implementation of the `resizeWindow` function will only throw an error.

The second link you provided (line 176) is still not the actual definition. It is just a C++ wrapper around the old C implementation. In older versions OpenCV's API was just C, no C+.

The actual definition of the function will depend on the GUI libraries available at compile time (as discovered by the `cmake` configuration step). But at least the C++ wrapper gives you some types to work with.

In general with OpenCV it is easier to start with the documentation and only look at the actual sources if that documentation is lacking.

The [doxygen documentation](http://docs.opencv.org/3.1.0) is the newest and will be the most up-to-date in the future. But don't ignore the older [Sphinx documentation](http://docs.opencv.org/3.0-last-rst/). It can be somewhat easier to navigate than the doxgen docs.

[This](http://docs.opencv.org/3.1.0/d7/dfc/group__highgui.html#ga9e80e080f7ef33f897e415358aee7f7e) is the documentation for `resizeWindow` with doxygen.
[This](http://docs.opencv.org/3.0-last-rst/modules/highgui/doc/user_interface.html#resizewindow) is the documenation for `resizeWindow` with Sphinx.

**Comment by Cortlandd** [comment]
Thanks you, this is helpful. I was already ahead of you on searching up the doxygen docs. I want to find the source to give me an idea of the logic, but truthfully, I may just wing it.

resizeWindow :: Window -> Int32 -> Int32 -> IO ()
resizeWindow namedWindow? 100 100 = _

My initial thinking it that there needs to of course be a created window before you can change its size? Hense the namedWindow argument.

**Comment by basvandijk** [comment]
Correct, you first need a created `Window` in order to resize it. To get inspiration on how to work with a `Window` look at the [imshow](https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/HighGui.hsc#L330) function. That will teach you how to unpack a `Window` and call a C++ function from OpenCV which does something with that window.

Good luck!

**Comment by Cortlandd** [comment]
Sorry for the bombard of questions but...whats happening here with `'S`? This must be Haskell wizardry @haskellbook hasn't taught me yet.
https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/HighGui.hsc#L332

**Comment by basvandijk** [comment]
No problem with the questions :-)

For the `resizeWindow` function you don't need to work with a `Mat` so you can ignore that for now.

But I'll try to explain it anyway (Note to self: add documentation for `Mat` that explains its phantom types):

As you probably have noticed a `Mat` is parameterised with [three phantom types](http://lumiguide.github.io/haskell-opencv/doc/OpenCV-Core-Types-Mat.html#t:Mat):

* *shape*: this specifies the shape of the matrix. For example it can specify whether the matrix is 1D, 2D, 3D, etc. It can even specify the dimensions of the matrix (i.e. the size of each dimension).

* *channels*: this specifies how many color channels there are per pixel. RGB images have 3 channels for example for red, green and blue.

* *depth*: this specifies the number of bits per matrix element.

A lot of functions in OpenCV require their input matrix to be of a certain type. For example the [warpAffine](https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/ImgProc/GeometricImgTransform.hsc#L162) function requires a 2D input matrix (it doesn't care about the number of channels nor about the depth). It also requires an affine transformation matrix which should be a 2x3 matrix with a single channel of doubles. We also know it should output a matrix with the same dimensions, the same number of channels and the same depth as the input matrix.

```haskell
warpAffine
    :: Mat ('S [height, width]) channels depth -- ^ Source image.
    -> Mat (ShapeT [2, 3]) ('S 1) ('S Double) -- ^ Affine transformation matrix.
    -> ...
    -> CvExcept (Mat ('S [height, width]) channels depth) -- ^ Transformed source image.
```

So each matrix property can be:

* Statically known (known at compile-time)

* Polymorphic (can be anything)

* Dynamically known. This means we don't know what the property is statically. It is determined at runtime.

We encode the Static/Dynamic choice with the [DS](https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/TypeLevel.hs#L44) *kind*. Note that we turn on the `DataKinds` extension so a datatype like `DS` gets turned into a kind and its constructors `D :: *` and `S :: * -> *` into type(constructor)s.

When we *statically* know what a certain property of a matrix should be we specify that property with an `S`. For example `S 1` when we know a matrix has 1 channel. When we know the property is only known at runtime we specify it with a `D`.

Encoding this in the type system allows for greater type safety. For example when we pass a 1D input matrix to `warpAffine` we get a type error instead of a runtime error.

I hope this make it a bit clearer. I'll try to add this story as documentation to the `Mat` type.

**Comment by Cortlandd** [comment]
I get the gist of it.

Also, a small suggestion: there should be a tips section under contribution:
Stuff like this: https://two-wrongs.com/using-withptr-from-inline-c-in-haskell 
is very useful. Especially for someone like myself who has not the slightest idea what I'm doing. Just winging it. Also note the "This Repository" search feature is your best friend, like Google.

So I think I'm getting the gist. Well, I wrapping my head around whats going on with the imshow function, etc.

```Haskell
--REFERENCES

{- OpenCV C++ function -}
-- void cv::resizeWindow ( const String & winname, int width, int  height )
{- Call some C -}
-- withCString :: String -> (CString -> IO a) -> IO a
{- Call this because I have to call a string pointer in the C++ function -}
-- withPtr :: a -> (Ptr (C a) -> IO b) -> IO b

resizeWindow :: Window -> Int -> Int -> IO ()
resizeWindow window width height = do
  -- Same thing with specifying a specific window
  C.withCString (windowName window) $ \c'name c'width c'height -> 
    withPtr [C.exp| void { cv::resizeWindow($(char * c'name), $(int c'width), $(int c'height)); } |]

-- believe im missing an argument after withPtr
```

Am I getting the hang of this contributing to other peoples projects thing? :smiling_imp:

**Comment by basvandijk** [comment]
Your definition has a few issues:

* We have a policy in haskell-opencv to use the most precise types for integer arguments. OpenCV uses `int` which is a 32-bit integer. So in Haskell we have to use `Int32` instead of `Int` for the width and height.

* Your application of `withCString` is wrong. It should be applied to the String `windowName window` which you do correctly. And it should be applied to a function which takes a `CString` and yields an `IO` operation. Your supplied function correctly takes the `c'name` but yields a function: `\c'width c'height -> ...`. Do note that you can directly pass the `width` and `height` to the inlined C++ code. See how simply we handle the `count` argument in [createTrackbar](https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/HighGui.hsc#L300) for example.

* Note that while looking at your definition I realised we had an inefficiency in our current `Window` operations. We store the name of the window as a `String` and turn that `String` into a `CString` for every operation on the Window. It would be better to do the `String -> CString` conversion once and store the `CString` in the Window. I just implemented this idea in: https://github.com/LumiGuide/haskell-opencv/commit/f7c62ec468ab3736a044530ccb3073182ad474b5. Take a look again at `imshow` how to unpack a `Window` now.

**Comment by Cortlandd** [comment]
Damn man I was wayy off.

You guy's are amazingly helpful.

```Haskell
resizeWindow :: Window -> Int32 -> Int32 -> IO ()
resizeWindow window width height =
  withWindow window $ \c'name ->
    [C.exp| 
      void { 
        cv::resizeWindow
          ( $(const * c'name)
          , $(int32_t width)
          , $(int32_t height) 
          ); 
      }
    |]
```
:smiling_imp:

**Comment by basvandijk** [comment]
I made another small change in: https://github.com/LumiGuide/haskell-opencv/commit/500e68e2b7d7c051d6d4527a4c68aa40b6ea6d4c. Now you can get the `c'name` directly from the `Window`. See [imshow](https://github.com/LumiGuide/haskell-opencv/blob/master/src/OpenCV/HighGui.hsc#L343) again.

**Comment by Cortlandd** [comment]
Wow I was wayy off. I think I'm getting the gist here...

```Haskell
resizeWindow :: Window -> Int32 -> Int32 -> IO ()
resizeWindow window width height =
  [C.exp| void { cv::resizeWindow( $(const * c'name), $(int32_t width), $(int32_t height) ); } |]
  where
    c'name :: CString
    c'name windowName window
```

**Comment by basvandijk** [comment]
Except for the `$(const * c'name)` which should be `$(char * c'name)` it looks fully correct. Well done.

If you can test this and turn it into a pull request with a line of documentation (eventually I would like to get to 100% documentation coverage), I will merge it.

**Comment by Cortlandd** [comment]
Understood. Oh and thank you for all your help! I can't wait to add more. Haar cascade is what I'm aiming for but that'll take some time.

**Comment by Cortlandd** [comment]
How should I approach having a line of documentation?

**Comment by basvandijk** [comment]
No, Nix is not a requirement. It's just a very convenient way to completely specify the required environment. 

As long as you can install opencv-3.1 and all the needed Haskell dependencies you should be good to go.

It would also be nice to support stack. I've never used it, have you?

**Comment by Cortlandd** [comment]
I always figured if something was initially packaged with cabal then stack commands can't be used? I will check it out. I'm wiping after a Ubuntu installation.

**Comment by Cortlandd** [comment]
I will create a branch of the repo that'll support stack to be reviewed by you guys.

**Comment by Cortlandd** [comment]
Really should open a new issue.

Getting this when trying to build:
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Video/MotionAnalysis.cpp
Any suggestions? I installed opencv 3.1.0, but not sure how to approach this

**Comment by basvandijk** [comment]
I believe this is a bug in opencv-3.1. First make sure your opencv is actually build with ippicv.

Then look at the second answer of this stackoverflow question:
http://askubuntu.com/questions/720528/opencv-compiling-error-ippicv/781072#781072

Also note that I move ippicv from the public to the private libs in its package-config file in the opencv-3.1.nix expression:
https://github.com/LumiGuide/haskell-opencv/blob/master/opencv-3.1.0.nix#L50
You probably need to do something similar.

**Comment by Cortlandd** [comment]
in my CMAKE I included ```-D WITH_IPP```. And I can find it it opencv/3rdparty/ippicv/etc etc etc

Checked, and ippicv is included.

so inside opencv.pc move -lippicv to private?

IS nix necessary for me to install?

**Comment by basvandijk** [comment]
> so inside opencv.pc move -lippicv to private?

Yes and also make sure to include the path to where the ippicv library is located using something like this:

```
Libs.private: -L$out/share/OpenCV/3rdparty/lib -lippicv
```

where `$out` is the path where you installed opencv-3.1.

> IS nix necessary for me to install?

Like I mentioned before, Nix is not a requirement. As long as you can install opencv-3.1 yourself you will be good to go. However, I strongly advise to use Nix since I already solved the problems that you are facing and encoded their solutions in the Nix expressions.

**Comment by Cortlandd** [comment]
Inside my /usr/local/share/OpenCV/3rdparty/lib is ```libippicv.a```

**Comment by Cortlandd** [comment]
Hmm, well I added it and I'm assuming it got it. Now I'm gettting this

```
opencv-0.0.0: configure
Configuring opencv-0.0.0...
opencv-0.0.0: build
Preprocessing library opencv-0.0.0...
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
In file included from Types.hsc:99:0:
/usr/local/include/opencv2/core.hpp:49:4: error: #error core.hpp header must be compiled as C++
 #  error core.hpp header must be compiled as C++
    ^
```

**Comment by Cortlandd** [comment]
Also alot of this when I attempt to ```stack build```

```
cortland@cerebral:~/Development/Haskell/haskell-opencv$ stack build
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Calib3d.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Core/ArrayOps.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Core/Types.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Core/Types/Internal.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Core/Types/Mat.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Core/Types/Mat/Internal.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Core/Types/Mat/Repa.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/C/PlacementNew.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Exception/Internal.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Features2d.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/HighGui.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgCodecs.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/ColorMaps.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/Drawing.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/GeometricImgTransform.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/ImgFiltering.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/MiscImgTransform.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/ObjectDetection.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/ImgProc/StructuralAnalysis.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Video.cpp
Warning: File listed in opencv.cabal file does not exist: src/OpenCV/Video/MotionAnalysis.cpp

```

**Comment by Cortlandd** [comment]
```
> cabal configure
> cabal build
```
output from ```cabal build```
```
ghc: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.
```

Gonna wait to use stack. Setup the configuration for it once I have resizewindow complete and can fully test haskell-opencv.

**Comment by roelvandijk** [comment]
When you get this:

    cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C

it means you are using a C compiler instead of a C++ compiler.

Any errors related to missing `.cpp` files is because of `stack` not processing the .cabal file in the same way as `cabal`. What happens is that `inline-c` generates these .cpp files as part of the template-haskell fase of compilation. These `.cpp` files must be compiled by the build tool before linking, so we must specify that they exist in the .cabal file. But they are generated during the build. 
We should perhaps ask the stack people how to handle such builds with stack.

**Comment by Cortlandd** [comment]
Well I've got everything going just about figured out. I'm doing alot fo research to get full compatibility with stack. Stack can be a pain.

At this point I am all setup and hacking at the HighGui functions. Thanks guys.

**Comment by basvandijk** [comment]
That message might be a warning. Have you tried a slightly bigger example like:

```haskell
import Control.Monad ( void )
import OpenCV
import qualified Data.ByteString as B

main :: IO ()
main = do
    img <- imdecode ImreadUnchanged <$> B.readFile "Lenna.png"
    window <- makeWindow "test"
    imshow window img
    void $ waitKey 10000
```

**Comment by basvandijk** [comment]
I just pushed [a patch](https://github.com/LumiGuide/haskell-opencv/commit/6b2a79fc1ee255a8a15144075eda6185c78754ba) that allows you to shorten the following:

```haskell
bracket (CV.makeWindow "test") CV.destroyWindow $ \window ->  ...
```

to just:

```haskell
CV.withWindow "test" $ \window -> ...
```

**Comment by basvandijk** [comment]
Note that I [added](https://github.com/LumiGuide/haskell-opencv/commit/fa644879325268360911dda0a044dde1f3949abe) an examples directory.

**Comment by Cortlandd** [comment]
Man, you're the best!

**Comment by Cortlandd** [comment]
@basvandijk 

```
As you probably have noticed a Mat is parameterised with three phantom types:

    shape: this specifies the shape of the matrix. For example it can specify whether the matrix is 1D, 2D, 3D, etc. It can even specify the dimensions of the matrix (i.e. the size of each dimension).

    channels: this specifies how many color channels there are per pixel. RGB images have 3 channels for example for red, green and blue.

    depth: this specifies the number of bits per matrix element.

A lot of functions in OpenCV require their input matrix to be of a certain type. For example the warpAffine function requires a 2D input matrix (it doesn't care about the number of channels nor about the depth). It also requires an affine transformation matrix which should be a 2x3 matrix with a single channel of doubles. We also know it should output a matrix with the same dimensions, the same number of channels and the same depth as the input matrix.

warpAffine
    :: Mat ('S [height, width]) channels depth -- ^ Source image.
    -> Mat (ShapeT [2, 3]) ('S 1) ('S Double) -- ^ Affine transformation matrix.
    -> ...
    -> CvExcept (Mat ('S [height, width]) channels depth) -- ^ Transformed source image.

So each matrix property can be:

    Statically known (known at compile-time)

    Polymorphic (can be anything)

    Dynamically known. This means we don't know what the property is statically. It is determined at runtime.

We encode the Static/Dynamic choice with the DS kind. Note that we turn on the DataKinds extension so a datatype like DS gets turned into a kind and its constructors D :: * and S :: * -> * into type(constructor)s.

When we statically know what a certain property of a matrix should be we specify that property with an S. For example S 1 when we know a matrix has 1 channel. When we know the property is only known at runtime we specify it with a D.

Encoding this in the type system allows for greater type safety. For example when we pass a 1D input matrix to warpAffine we get a type error instead of a runtime error.
```

This has to be documented.
