### ISSUE TITLE
Implementing the correct type.

### ISSUE THREAD

**Issue by Cortlandd** [LumiGuide/haskell-opencv#8]
So I'm attempting to implement the watershed function from ImgProc. According to the [docs](http://docs.opencv.org/3.1.0/d7/d1b/group__imgproc__misc.html#ga3267243e4d3f95165d55a618c65ac6e1) . When the docs specifies that argument
```InputArray image``` is ```Input 8-bit 3-channel image ```
and argument
```InputOutputArray markers ``` is ```Input/output 32-bit single-channel image (map) of markers. It should have the same size as image .```

What are the steps for implementing this? Implementing 3bit channels, etc. What is the haskell-opencv alias for InputOutputArray, etc?

**Comment by Cortlandd** [comment]
That's perfect, thanks. But why PrimMonad?

**Comment by roelvandijk** [comment]
Because I presume that the implementation of `watershed` will have no other observable effects than writing to the `markers` matrix. This is expressed by the state type variable of the `MutMat`: `PrimState m`. Any mutations to the `MutMat` can only be observed inside of the [strict state thread](https://wiki.haskell.org/Monad/ST).

`PrimMonad` allows the user to run the `watershed` function in either `IO` or `ST` (or any other type that is an instance of `PrimMonad`). This allows you to use `watershed` in non-IO code.

See the various drawing functions for examples.

**Comment by basvandijk** [comment]
[We now have a binding to `watershed`](https://github.com/LumiGuide/haskell-opencv/commit/4da5fd2a11042eab49bd3ec7db0a0d702dc9c90e). So this can be closed.
